_name_folder_ = FALL-INTO-OBLIVION
_location_of_folder_ = FALL-INTO-OBLIVION

run:
	python2 daemon.py &

cli:
	python2 cli.py

files:
	echo "this is a test 1" > file1
	echo "this is a test 2" > file2
	echo "this is a test 3" > file3

clean:
	echo "delete all the garbage from the folder"
	rm -r $(HOME)/$(_name_folder_)